// Generated by gencpp from file phidgets_msgs/SetDigitalOutput.msg
// DO NOT EDIT!


#ifndef PHIDGETS_MSGS_MESSAGE_SETDIGITALOUTPUT_H
#define PHIDGETS_MSGS_MESSAGE_SETDIGITALOUTPUT_H

#include <ros/service_traits.h>


#include <phidgets_msgs/SetDigitalOutputRequest.h>
#include <phidgets_msgs/SetDigitalOutputResponse.h>


namespace phidgets_msgs
{

struct SetDigitalOutput
{

typedef SetDigitalOutputRequest Request;
typedef SetDigitalOutputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDigitalOutput
} // namespace phidgets_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phidgets_msgs::SetDigitalOutput > {
  static const char* value()
  {
    return "8496af00b3dd95e3884fd81d8e38f019";
  }

  static const char* value(const ::phidgets_msgs::SetDigitalOutput&) { return value(); }
};

template<>
struct DataType< ::phidgets_msgs::SetDigitalOutput > {
  static const char* value()
  {
    return "phidgets_msgs/SetDigitalOutput";
  }

  static const char* value(const ::phidgets_msgs::SetDigitalOutput&) { return value(); }
};


// service_traits::MD5Sum< ::phidgets_msgs::SetDigitalOutputRequest> should match
// service_traits::MD5Sum< ::phidgets_msgs::SetDigitalOutput >
template<>
struct MD5Sum< ::phidgets_msgs::SetDigitalOutputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phidgets_msgs::SetDigitalOutput >::value();
  }
  static const char* value(const ::phidgets_msgs::SetDigitalOutputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phidgets_msgs::SetDigitalOutputRequest> should match
// service_traits::DataType< ::phidgets_msgs::SetDigitalOutput >
template<>
struct DataType< ::phidgets_msgs::SetDigitalOutputRequest>
{
  static const char* value()
  {
    return DataType< ::phidgets_msgs::SetDigitalOutput >::value();
  }
  static const char* value(const ::phidgets_msgs::SetDigitalOutputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phidgets_msgs::SetDigitalOutputResponse> should match
// service_traits::MD5Sum< ::phidgets_msgs::SetDigitalOutput >
template<>
struct MD5Sum< ::phidgets_msgs::SetDigitalOutputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phidgets_msgs::SetDigitalOutput >::value();
  }
  static const char* value(const ::phidgets_msgs::SetDigitalOutputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phidgets_msgs::SetDigitalOutputResponse> should match
// service_traits::DataType< ::phidgets_msgs::SetDigitalOutput >
template<>
struct DataType< ::phidgets_msgs::SetDigitalOutputResponse>
{
  static const char* value()
  {
    return DataType< ::phidgets_msgs::SetDigitalOutput >::value();
  }
  static const char* value(const ::phidgets_msgs::SetDigitalOutputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHIDGETS_MSGS_MESSAGE_SETDIGITALOUTPUT_H
