(cl:defpackage phidgets_msgs-srv
  (:use )
  (:export
   "SETANALOGOUTPUT"
   "<SETANALOGOUTPUT-REQUEST>"
   "SETANALOGOUTPUT-REQUEST"
   "<SETANALOGOUTPUT-RESPONSE>"
   "SETANALOGOUTPUT-RESPONSE"
   "SETDIGITALOUTPUT"
   "<SETDIGITALOUTPUT-REQUEST>"
   "SETDIGITALOUTPUT-REQUEST"
   "<SETDIGITALOUTPUT-RESPONSE>"
   "SETDIGITALOUTPUT-RESPONSE"
  ))

